variables:
- group: DOKKU_VARIABLES
- name: DOKKU_PROJECT_NAME
  value: sglegis

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(SSH_KNOWN_HOSTS_ENTRY)
    sshPublicKey: $(SSH_PUBLIC_KEY)
    sshKeySecureFile: $(SSH_PRIVATE_KEY_FILENAME)
- script: |
    git remote add dokku dokku@$DOKKU_SERVER:$DOKKU_PROJECT_NAME
    git remote -v
    git push dokku HEAD:master --force
  displayName: 'Deploy to Dokku'
