variables:
- group: DOKKU_VARIABLES
- name: DOKKU_PROJECT_NAME
  value: dev-sglegis

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
# Install sequelize
- script: "npm install -g sequelize"
  displayName: "install sequelize"

# Install a driver, like mysql2 
- script: "npm install -g mysql2"
  displayName: "install mysql2"

# Install the sequelize CLI
- script: "npm install -g sequelize-cli"
  displayName: "install sequelize-cli"

# Install the migration
- script: "sequelize db:migrate"
  displayName: "run migration"

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(SSH_KNOWN_HOSTS_ENTRY)
    sshPublicKey: $(SSH_PUBLIC_KEY)
    sshKeySecureFile: $(SSH_PRIVATE_KEY_FILENAME)
- script: |
    git remote add dokku dokku@$DOKKU_SERVER:$DOKKU_PROJECT_NAME
    
    echo 'Remotes on git'
    git remote -v

    echo 'Dokku push'
    git push dokku develop:master --force
  displayName: 'Deploy to Dokku'