variables:
- group: DOKKU_VARIABLES
- name: DOKKU_PROJECT_NAME
  value: dev-sglegis

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: $(SSH_KNOWN_HOSTS_ENTRY)
    sshPublicKey: $(SSH_PUBLIC_KEY)
    sshKeySecureFile: $(SSH_PRIVATE_KEY_FILENAME)
- script: |
    git remote add dokku dokku@$DOKKU_SERVER:$DOKKU_PROJECT_NAME
    
    echo 'Remotes on git'
    git remote -v

    echo 'Dokku push'
    git push dokku develop:master --force
  displayName: 'Deploy to Dokku'